"""initial schema with theme/breadcrumb model

Revision ID: 32dfd59355c0
Revises: 
Create Date: 2025-11-07 14:18:50.649157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32dfd59355c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_tag_name_lower_idx', 'tag', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('theme',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description_md', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visibility', sa.Enum('draft', 'published', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_theme_title', 'theme', ['title'], unique=False)
    op.create_table('breadcrumb',
    sa.Column('body_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_breadcrumb_created_at', 'breadcrumb', ['created_at'], unique=False)
    op.create_table('themetag',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('theme_id', 'tag_id')
    )
    op.create_index(op.f('ix_themetag_tag_id'), 'themetag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themetag_tag_id'), table_name='themetag')
    op.drop_table('themetag')
    op.drop_index('idx_breadcrumb_created_at', table_name='breadcrumb')
    op.drop_table('breadcrumb')
    op.drop_index('idx_theme_title', table_name='theme')
    op.drop_table('theme')
    op.drop_index('uq_tag_name_lower_idx', table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
