"""initial schema

Revision ID: 8d16b19e67d9
Revises: 
Create Date: 2025-11-05 16:05:50.154544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d16b19e67d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_tag_name_lower_idx', 'tag', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('unit',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unit_name', 'unit', ['name'], unique=False)
    op.create_table('crumb',
    sa.Column('body_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.Enum('draft', 'published', name='visibility'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crumb_created_at', 'crumb', ['created_at'], unique=False)
    op.create_table('crumbtag',
    sa.Column('crumb_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crumb_id'], ['crumb.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('crumb_id', 'tag_id')
    )
    op.create_index(op.f('ix_crumbtag_tag_id'), 'crumbtag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crumbtag_tag_id'), table_name='crumbtag')
    op.drop_table('crumbtag')
    op.drop_index('idx_crumb_created_at', table_name='crumb')
    op.drop_table('crumb')
    op.drop_index('idx_unit_name', table_name='unit')
    op.drop_table('unit')
    op.drop_index('uq_tag_name_lower_idx', table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
