"""add trail notes tables: digest, subscriber, digest_send

Revision ID: 1ac706c0dce9
Revises: 481dfeec970f
Create Date: 2026-02-24 02:42:37.295223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1ac706c0dce9'
down_revision: Union[str, Sequence[str], None] = '481dfeec970f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'sent', name='digeststatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', name='uq_digest_period_start')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('confirmation_token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('unsubscribe_token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_subscriber_email')
    )
    op.create_table('digest_send',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='sendstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['digest_id'], ['digest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_id', 'subscriber_id', name='uq_digest_send_digest_subscriber')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_send')
    op.drop_table('subscriber')
    op.drop_table('digest')
    # ### end Alembic commands ###
