/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WriterRouteRouteImport } from './routes/writer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriterIndexRouteImport } from './routes/writer/index'
import { Route as WriterThemesThemeIdRouteImport } from './routes/writer/themes.$themeId'
import { Route as TagsTagNameThemesRouteImport } from './routes/tags.$tagName.themes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterRouteRoute = WriterRouteRouteImport.update({
  id: '/writer',
  path: '/writer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterIndexRoute = WriterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WriterRouteRoute,
} as any)
const WriterThemesThemeIdRoute = WriterThemesThemeIdRouteImport.update({
  id: '/themes/$themeId',
  path: '/themes/$themeId',
  getParentRoute: () => WriterRouteRoute,
} as any)
const TagsTagNameThemesRoute = TagsTagNameThemesRouteImport.update({
  id: '/tags/$tagName/themes',
  path: '/tags/$tagName/themes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/writer': typeof WriterRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/writer/': typeof WriterIndexRoute
  '/tags/$tagName/themes': typeof TagsTagNameThemesRoute
  '/writer/themes/$themeId': typeof WriterThemesThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/writer': typeof WriterIndexRoute
  '/tags/$tagName/themes': typeof TagsTagNameThemesRoute
  '/writer/themes/$themeId': typeof WriterThemesThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/writer': typeof WriterRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/writer/': typeof WriterIndexRoute
  '/tags/$tagName/themes': typeof TagsTagNameThemesRoute
  '/writer/themes/$themeId': typeof WriterThemesThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/writer'
    | '/about'
    | '/login'
    | '/writer/'
    | '/tags/$tagName/themes'
    | '/writer/themes/$themeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/writer'
    | '/tags/$tagName/themes'
    | '/writer/themes/$themeId'
  id:
    | '__root__'
    | '/'
    | '/writer'
    | '/about'
    | '/login'
    | '/writer/'
    | '/tags/$tagName/themes'
    | '/writer/themes/$themeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WriterRouteRoute: typeof WriterRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  TagsTagNameThemesRoute: typeof TagsTagNameThemesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer': {
      id: '/writer'
      path: '/writer'
      fullPath: '/writer'
      preLoaderRoute: typeof WriterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/': {
      id: '/writer/'
      path: '/'
      fullPath: '/writer/'
      preLoaderRoute: typeof WriterIndexRouteImport
      parentRoute: typeof WriterRouteRoute
    }
    '/writer/themes/$themeId': {
      id: '/writer/themes/$themeId'
      path: '/themes/$themeId'
      fullPath: '/writer/themes/$themeId'
      preLoaderRoute: typeof WriterThemesThemeIdRouteImport
      parentRoute: typeof WriterRouteRoute
    }
    '/tags/$tagName/themes': {
      id: '/tags/$tagName/themes'
      path: '/tags/$tagName/themes'
      fullPath: '/tags/$tagName/themes'
      preLoaderRoute: typeof TagsTagNameThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WriterRouteRouteChildren {
  WriterIndexRoute: typeof WriterIndexRoute
  WriterThemesThemeIdRoute: typeof WriterThemesThemeIdRoute
}

const WriterRouteRouteChildren: WriterRouteRouteChildren = {
  WriterIndexRoute: WriterIndexRoute,
  WriterThemesThemeIdRoute: WriterThemesThemeIdRoute,
}

const WriterRouteRouteWithChildren = WriterRouteRoute._addFileChildren(
  WriterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WriterRouteRoute: WriterRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  TagsTagNameThemesRoute: TagsTagNameThemesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
